### ISSUE TITLE
Event name is not parsed correct if fired with identifier instead string constant

### ISSUE THREAD

**Issue by alexprey** [alexprey/sveltedoc-parser#1]
Event name is not parsed correct if fired with identifier instead string constant

```js
import { createEventDispatcher } from 'svelte';
const dispatch = createEventDispatcher();

const CLOSE_EVENT_NAME = 'modalWasClosed';
dispatch(CLOSE_EVENT_NAME);
```

## Actual result 

```json
{
    "events": [
        {
            "name": "****unhandled-event-name****"
        }
    ]
}
```

## Expected result

```json
{
    "events": [
        {
            "name": "click"
        }
    ]
}
```

**UPD.** At 4.0.0 point this issue are partially fixed.

- [x] Support the top-level plain constants (`EVENT_MODAL_CLOSE`)
- [x] Support the top-level object-level constants (`EVENT.MODAL.CLOSE`)
- [x] Support the top-level object-level constants with accessing by index getter (`EVENT['MODAL']['CLOSE']`). Actually, I'm not sure that this are required

**Comment by TheComputerM** [comment]
Yeah, having the same problem with svelte 3

**Comment by TheComputerM** [comment]
If there is something like:
```js
function dismiss() {
  visible = false;
  dispatch('dismiss', {
    visible,
  });
}
```

The event `dismiss` is properly shown in the doc, but if the function is exported:
```js
export function dismiss() {
  visible = false;
  dispatch('dismiss', {
    visible,
  });
}
```

The event `dismiss` is not shown at all.

**Comment by alexprey** [comment]
@TheComputerM it looks like a new issue, I'm create a new one, thanks you for reporting!

**Comment by soft-decay** [comment]
Hi @alexprey. Hoped you had good holidays.

This is a very old issue, but I saw it was also affecting the v3 parser, so I worked on it and opened a PR (#46) for a fix.
It allows basic support for identifier parsing of events:
- can only recognize top level identifiers
- nested identifiers in `MemberExpression` have to be dot notation only (`computed` with brackets not supported) 
- Supports only nested `Literal` and `ObjectExpression`

If you want to see support for more types of node, or if you think it should support bracket notation for identifier parsing, let me know. I also left some TODOs in the PR that I'm going to complete soon.

**Comment by alexprey** [comment]
At 4.0.0 point this issue are partially fixed. However to complete this issue we need more work. Not sure that supporting of left cases should be solved in the area of this library. For example - support of imported identifiers. Actually the library dont have any logic to resolve import files or analyze them. But if we can support that it will be nice.
I suppose that I can mark this isuue as low-priority, due we cover basic cases of identifier usage in event names.

**Comment by soft-decay** [comment]
The bracket notation support would just be nice to have, but is not that important.

However, supporting imports parsing is a whole other story, and I feel like it should have its own separate issue. The way I see it, if the library supports the resolution and parsing of imported files, imported identifiers become top level identifiers, so the same logic can be applied to them.

What do you think about creating a new issue that is more specific to the new problem (Resolve imported identifiers)?

**Comment by alexprey** [comment]
You are right, the imported identifiers handling looks like a new story. Keep only bracets notation in this issue and create a new one to support external references

**Comment by alexprey** [comment]
@soft-decay I create a new issue to discuss the architecture for imported identifiers - #48. I mark it with low priority, due TypeScript support is more important for that.

**Comment by soft-decay** [comment]
I added support for bracket notation with string literals in this PR #54. I did not implement nested computed Identifier. e.g. :

```js
dispatch(EVENT[OTHER.CONSTANT].NOTIFY) // Not supported
dispatch(EVENT["NESTED"].NOTIFY) // Supported
```

**Comment by alexprey** [comment]
> dispatch(EVENT[OTHER.CONSTANT].NOTIFY) // Not supported

I think that is out of scope, so ok
