### ISSUE TITLE
How to add descriptions for actions and slots in Svelte v3

### ISSUE THREAD

**Issue by TheComputerM** [alexprey/sveltedoc-parser#23]
Looking at the README, it is very hard to understand how to add descriptions for actions and slots in Svelte v3

**Comment by alexprey** [comment]
Hi!
Hm, I think that is a good idea to add example of documentation that can be parsed by this package.
Answering on your question, slots can be described by following format:

```html
<div>
   <!-- This is a slot with `title` name -->
    <slot name="title">
        Default title
    </slot>
    <slot name="body">
        Default body content
    </slot>
</div>
```

What you mean for `actions in svelte3`? Actually in Svelte 3 actions is just a functions https://svelte.dev/docs#use_action and that can be described by JSDoc

```js
/**
 * The action description
 * @param {HTMLElement} node
 */
function action(node) {
}
```

**Comment by TheComputerM** [comment]
Ok thanks, I thought you had to do something with `use:Action`

**Comment by alexprey** [comment]
Actually no, because it is a part of components internal stuff, not about component description. But, I think that it can be helpful and I can mark component-defined methods with `action` flag.
