### ISSUE TITLE
Does not generate variable for `export {variable as var}`

### ISSUE THREAD

**Issue by TheComputerM** [alexprey/sveltedoc-parser#26]
Sample:
- Component: https://github.com/TheComputerM/svelte-materialify/blob/master/packages/svelte-materialify/src/components/Button/Button.svelte
- Result: https://github.com/TheComputerM/svelte-materialify/blob/master/packages/api-generator/src/Button.json

Expected:
Generate entry for `class` prop

Output:
Does not generate any entry for `class` or even `classes`

**Comment by alexprey** [comment]
Thanks for reporint an issue!
Fix it and publish new version of package to use 😉

```js
/**
 * Comments can be placed here and it must be inhereted to export prop instance
 */
const classes = [ 'btn' ];

export { classes as class };
```
```js
[
 { 
     "name": "classes", 
     "visibility": "private", 
     "description": "Comments can be placed here and it must be inhereted to export prop instance" 
 },
 { 
    "name": "class", 
    "visibility": "public", 
    "description": "Comments can be placed here and it must be inhereted to export prop instance", 
    "localName": "classes" 
 }
]
```

**Comment by TheComputerM** [comment]
Thank you very much my dude.

**Comment by alexprey** [comment]
NP, just let me know if you have any other issues with that
