### ISSUE TITLE
Propogated events in markup should be parsed even it was before handled

### ISSUE THREAD

**Issue by TheComputerM** [alexprey/sveltedoc-parser#31]
[File](https://github.com/TheComputerM/svelte-materialify/blob/master/packages/svelte-materialify/src/components/Checkbox/Checkbox.svelte)

[Output](https://github.com/TheComputerM/svelte-materialify/blob/master/packages/api-generator/src/Checkbox.json)

The `on:change` event attached to the checkbox input is not being registered in the output.

**Comment by alexprey** [comment]
Fixed
