### ISSUE TITLE
Event is not registered when dispatched from functions used as a parameters of another functions

### ISSUE THREAD

**Issue by TheComputerM** [alexprey/sveltedoc-parser#32]
[File](https://github.com/TheComputerM/svelte-materialify/blob/c6b8a7889e86eb05b7f645401d3fb7d42f2dd819/packages/svelte-materialify/src/components/ExpansionPanels/ExpansionPanel.svelte#L63)

[Output](https://github.com/TheComputerM/svelte-materialify/blob/c6b8a7889e86eb05b7f645401d3fb7d42f2dd819/packages/api-generator/src/ExpansionPanel.json#L85)

Event dispatched not being registered.

**Comment by alexprey** [comment]
Fixed
