### ISSUE TITLE
Object literals not supported in @type

### ISSUE THREAD

**Issue by soft-decay** [alexprey/sveltedoc-parser#35]
Adding this to `examples/Button.svelte`:

```javascript
/**
 * Additional options for the button.
 * @type {{ rtl: boolean, lang: string }}
 */
export let options = { rtl: false, lang: 'en-us' };
```

and running `yarn generate-examples` produces this `.json` (only showing relevant part) :

```json
// ...
// Last item of data
{   
    "keywords": [
        {
            "name": "type",
            "description": "{{ rtl: boolean, lang: string }}"
        }
    ],
    "visibility": "public",
    "description": "Additional options for the button.",
    "name": "options",
    "kind": "let",
    "static": false,
    "readonly": false,
    "type": {
        "kind": "type",
        "text": "{ rtl: boolean, lang: string",
        "type": "{ rtl: boolean, lang: string"
    }
}
// ...
```

where `type.text` and `type.type` lose the closing curly brace.

I have a fix ready, but it adds a new dependency to the project (`"xregexp": "^4.4.0"`).
If you're open to this idea, I can create a PR.
I also added jsdoc unit tests for Object literals and nested literals, but only for `'Parse type keyword'`.

**Comment by alexprey** [comment]
Hi! Thanks for the issue, that interesting case, I'm try to think how it can be fixed w/o adding the new dependency

**Comment by soft-decay** [comment]
Yes I understand that. My first idea was to solve it with pure regex, but javascript regex does not provide the PCRE recursive parameter `(?R)` (see [Regex Recursion (Matching Nested Constructs)](http://blog.stevenlevithan.com/archives/regex-recursion)). So you can only match to a predetermined depth of matching things, which could be enough.

But your comment made me realize that the matcher for types does not need to ignore closing `{` :

```diff
- const TYPE = '\\{([^\\}]*)\\}';
+ const TYPE = '\\{(.*)\\}';
```

It's not perfect but it passes all current tests plus the tests I made for Object literals and nested literals.
Should I create a PR for it?

**Comment by alexprey** [comment]
Ok, looks good as a quick fix. Please create PR and I'm merge it and then publish a new version 😄

**Comment by alexprey** [comment]
Thanks for a fix!
I'm publish it as a version 3.0.5
