### ISSUE TITLE
Comment for data etc. is not provided if it has any keyword

### ISSUE THREAD

**Issue by ArdenIvanov** [alexprey/sveltedoc-parser#4]
Comments like that are not attached to the description
```
/** @type {string} This is not parsed */
```

**Comment by alexprey** [comment]
@ArdenIvanov this is not a valid JSDoc syntax http://usejsdoc.org/tags-type.html, `@type` tag don't have a description part, like in `@param` tag

**Comment by tyv** [comment]
@alexprey this is not working as well: 

```js
  /**
   * External `text` prop description.
   * @type {string}
   */
  export let text = "";
```

result
```js
  {
      keywords: [],
      visibility: 'public',
      description: 'External `text` prop description.',
      name: 'text',
      kind: 'let',
      static: false,
      readonly: false,
      type: 'any',
      importPath: undefined,
      originalName: undefined
    }
```

**Comment by tyv** [comment]
descriptions at the components level are not working as well. 
this example, does not wok for me https://github.com/alexprey/sveltedoc-parser/blob/master/test/svelte3/integration/components/components.import.svelte

**Comment by alexprey** [comment]
Hi @tyv, 
sorry for long delay.
But looks like this PR https://github.com/alexprey/sveltedoc-parser/pull/20 fix both your problems
