### ISSUE TITLE
Remove deprecated keys for 4.0.0 release

### ISSUE THREAD

**Issue by soft-decay** [alexprey/sveltedoc-parser#41]
This is already commited in this [PR](#40) but I'm opening an issue just in case a discussion is needed on what to remove/keep/rename.

**Comment by TheComputerM** [comment]
The current output is:
```
"keywords": [
                {
                    "name": "name_of_keyword",
                    "description": "..."
                }
            ],
```

It would be better if:
```
"keywords": {
  "name_of_keyword": {description: "..."}
}
```

**Comment by soft-decay** [comment]
Hi @TheComputerM,

The reason keywords are output as an array is that keywords are non-unique (e.g. a function could have 2 or more `@param`). If you have a use-case example, maybe we can find some other solution to what you are trying to do.

**Comment by TheComputerM** [comment]
Oooh, understood, just thinking that it is tedious to filter out stuff like: `.filter((x) => x.name==='name')`

**Comment by alexprey** [comment]
@TheComputerM I think that it is not required, it really can be usufully, but only for specific cases, so I prefer to keep structure siplier. If you want to use dictionary for accessing to keywords, you can remap values in your code and work with that. For example:

```
const keywordMap = keywords.reduce((carry, keyword) => {
    if (carry[keyword.name]) {
        carry[keyword.name].push(keyword);
    } else {
        carry[keyword.name] = [ keyword ]
    }
}, {});
```
