### ISSUE TITLE
Fix typings to match the actual exported api format

### ISSUE THREAD

**Issue by soft-decay** [alexprey/sveltedoc-parser#42]
@alexprey As you said, the typings should be updated to match the actual api.

First thing I found is :

```typescript
export interface SvelteDataItem extends ISvelteItem {
// ...
/**
 * The default value of property, if provided.
 */
value?: any;
// ...
}
```

but the exported key is actually `defaultValue` (see the [example Button](https://github.com/alexprey/sveltedoc-parser/blob/afb6115cf91144503e175b95b8bab4f7917f837b/examples/Button.json#L23)).

Which one should be kept?

**Comment by alexprey** [comment]
Thanks for that catch, I'm fix it. And also update the API for default value of optional parameter

**Comment by soft-decay** [comment]
I just saw you pushed modifications for the typings, but I made a mistake when I renamed `SvelteMethodArgumentItem` to `SvelteMethodParamItem`.

It should be:

```typescript
/**
 * @deprecated
 */
export type SvelteMethodArgumentItem = SvelteMethodParamItem;
```

and you can delete `type SvelteArgItem` and `type SvelteArgumentItem`, I added them by mistake #40, so they were never released.

**Comment by alexprey** [comment]
Ok, thanks for note about that, I'm remove this types from typings file.
