### ISSUE TITLE
`lastComment` is not consumed when emitted in `onopentag` of the HtmlParser callback handler

### ISSUE THREAD

**Issue by soft-decay** [alexprey/sveltedoc-parser#47]
in `onattribute`, `lastComment` is comsumed (emitted and set to `null`):

```javascript
if (!hasOwnProperty(this.eventsEmitted, baseEvent.name)) {
    this.eventsEmitted[baseEvent.name] = baseEvent;

    this.parseKeywords(comment.keywords, baseEvent);
    this.emit('event', baseEvent);
}

lastComment = null;
```

but it is only emitted in `onopentag`. It should be removed to prevent its application to other elements.

Example :
In https://svelte-materialify.vercel.app/api/TextField/, the comment '_Slot for prepend inside the input._' should only be applied to `<slot name="prepend" />` but is also applied to `<slot />`, `<slot name="content" />`, and `on:focus`.

**Comment by alexprey** [comment]
Hi, I'll try to look at this

**Comment by alexprey** [comment]
Hi @soft-decay! 
I'm fix this issue in this commit https://github.com/alexprey/sveltedoc-parser/commit/9a7bfc4b4b6d13e75a0ee294bf24040262d0e426. This commit based on refactoring branch, I'm add few simple tests for that, but it will be good if you can check fix on your examples and approve that this fix are correct.

Thanks!

**Comment by soft-decay** [comment]
Hi @alexprey,

Just checked and the problem is fixed in the example provided. Thanks.

**Comment by alexprey** [comment]
Perfect! So! I'll merge that
