### ISSUE TITLE
Investigate typescript integration

### ISSUE THREAD

**Issue by alexprey** [alexprey/sveltedoc-parser#49]
Think about API to able provide functions to handle different integration, the key goal - add support of typescript, the second goal - support of another processors. For example, it can be similar like `svelte.preprocess` option, that can provide smooth integration with already exists processors.

In ideal case use TS or babel compiler that can provide information about types.

**Comment by soft-decay** [comment]
After a quick look at some of the typescript compatible parsers (mainly [typescript](https://github.com/basarat/byots), [@babel/parser](https://github.com/babel/babel/tree/main/packages/babel-parser), and [@typescript-eslint/parser](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser)) its seems the one that is the closest to the currently used parser ([espree](https://github.com/eslint/espree)) is @typescript-eslint/parser. The node structure and naming seems identical at first glance (other than additional type information), but I have not looked in depth.

The @babel/parser also seems good, but there is a difference in the node types (e.g. I spotted that the node type `Literal` becomes different nodes such as `StringLiteral`, `BooleanLiteral`, etc).

Do you think AST similarities should be a main consideration, or did you have other considerations in mind?

**Comment by alexprey** [comment]
Using the  [typescript](https://github.com/basarat/byots), and [@typescript-eslint/parser](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser) is a good at the first look and can reach out key goal.
At the same time, [@babel/parser](https://github.com/babel/babel/tree/main/packages/babel-parser) is popular and used in different projects and build processes. Also it is flexiable solution, that allow to support different languages in the future.

PS. Thanks for the link to astexplorer, I'll look into that in details

**Comment by alexprey** [comment]
I'm start to reviewing the libraries provided by @soft-decay. Due this library already used in svelte-intellisense vscode extension, so it should work fast as possible. So, I plan to do performance tests and test library APIs to usability. I hope that I can back with results in few days

**Comment by alexprey** [comment]
Ok, I'm done with performance measurement with babel-parser, eslint-parser and direct typescript parser. I collect around 2000 source svelte files contained 1758 KB of TS & JS svelte mix.

| Parser | Error rate | Avg. per file (ms) | Speed (B/ms) |
| ------ | ---------- | ------------------ | ------------ |
| **babel** | 1.4% | 1.418 | 595.970 |
| **eslint** | 1.4% | 4.793 | 176.288 |
| **typescript** | 0.0% | 0.777 | 1087.253 |

Based on this results I think that we need to swith to direct typescript compiler to parse source files. But I'm not sure that it can be simple to use.

I plan to introduce this performance testing in CI process, but it need to decide where we should host the test files. The current scope of files I take from github search output by few different quries.

Also, during that I found few issue with `parseFileStructureFromContent` method. I'll create separate issue for that

**Comment by binarious** [comment]
Is there any WIP branch or workaround? We'd like to use this library in a TypeScript svelte project.

**Comment by alexprey** [comment]
Ok, keep going with native `typescript` library.
