### ISSUE TITLE
Improve documentation following v4.0.0 release

### ISSUE THREAD

**Issue by soft-decay** [alexprey/sveltedoc-parser#51]
I think it would be a good time to update the README.

I was thinking of the following changes and improvements:
- [x] Split the `Features` section into 3 subsections (Common Features, Svelte 2 Features, Svelte 3 Features)
  > Reason : I think it's a little hard to read which feature is supported by which version.
- [x] Change the format of `Supported feature names` to a table with check marks
  > Reason : Improved readability
- [x] Add an advanced example in `Usage` to showcase some of the other options
- [x] Generate Table of Contents
 
- [x] Minor changes, corrections, and proofreading
  - Rename `Configuration` to `Options` (so it has the same name everywhere in the project)

I submitted a PR #52 with the proposed changes.

**Comment by alexprey** [comment]
Thanks, just today I look at readme and think about the same 👍
