### ISSUE TITLE
(small) Add final newline?

### ISSUE THREAD

**Issue by Florian-Schoenherr** [alexprey/sveltedoc-parser#59]
Either we have implemented something wrong or the parser doesn't spit out a final newline (in the generated json).
If it's on your end, it would be nice to have.
(But I actually don't know if that final newline is needed, just know it's best practice because unix)

**Comment by alexprey** [comment]
Hi @Florian-Schoenherr, can you please describe in detail what you do and what you get? I'm not understand what you mean... The parser failed when works with files ended by empty line at the end, or you propose to add new empty lines to all source files in the code of parser?

**Comment by Florian-Schoenherr** [comment]
Oh, sorry, I just mean after parsing there is no final newline after parsing (in the generated json).
We are doing this:
```js
async function generateJSON(filename) {
  const doc = await sveltedoc.parse({ filename, ...defaults });
  const name = basename(filename, '.svelte');
  await writeFile(`./src/${name}.json`, fmt(doc, format), (err) => {
    if (err) throw err;
    console.log(`${name}.json has been saved`);
  });
}
```
It could also be a fault of json-format.

**Comment by alexprey** [comment]
Ok, thanks! The parser just provide structured object with all metadata that can be parsed. And then you can do with that anything.
You need to check your `fmt` method to ensure that it works correctly. This issue is not related to the parser. 

But, anyway thanks for using it and thanks for a question!

**Comment by Florian-Schoenherr** [comment]
Ah so it is a js object but when writing to a file it doesn't have a new line. Thank you!
