### ISSUE TITLE
Parse imported type from jsdoc

### ISSUE THREAD

**Issue by alexprey** [alexprey/sveltedoc-parser#60]
The following parameter type:
```js
 * @param {import('./typings.d.ts')}.ImpotedObjectType} The parameter description.
```
parsed as `import('./typings.d.ts').ImportedObjectType`, but it's is a good to extend parameter property to have additional information about path of importing and provide the normal clear type name.
```json
{
    "kind": "type",
    "type": "ImportedObjectType",
    "importPath": "./typings.d.ts"
}
```

**Comment by soft-decay** [comment]
This would be nice, but I just want to throw out there that it is not jsdoc-specific:
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#import-types

Still I think it would be worthwhile addition.

**Comment by alexprey** [comment]
Hm, thanks! So, I think that is better to support both formats
